// 한 줄로 실행하는 간단한 모니터링 코드
// 브라우저 콘솔에 이 한 줄만 붙여넣으세요:

(function(){const ws=new WebSocket('ws://localhost:3901');ws.onopen=()=>{console.log('✅ 모니터링 시작!');document.body.style.border='3px solid #10b981';const e=console.error;console.error=function(...a){const m=a.join(' ');if(m.includes('Text content does not match server-rendered HTML')||m.includes('Server:')&&m.includes('Client:')){ws.send(JSON.stringify({type:'hydration-error',message:m,priority:'high',timestamp:new Date().toISOString()}));console.log('🔍 Hydration 오류 감지:',m);}ws.send(JSON.stringify({type:'console-error',message:m,priority:'high',timestamp:new Date().toISOString()}));e.apply(console,a);};window.addEventListener('error',(ev)=>{const m=ev.message||'';if(m.includes('Text content does not match server-rendered HTML')||m.includes('hydration')||(m.includes('Server:')&&m.includes('Client:'))){ws.send(JSON.stringify({type:'hydration-error',message:m,priority:'high',timestamp:new Date().toISOString()}));console.log('🔍 Hydration 오류 감지:',m);}ws.send(JSON.stringify({type:'window-error',message:m,filename:ev.filename,lineno:ev.lineno,colno:ev.colno,priority:'high',timestamp:new Date().toISOString()}));});window.addEventListener('unhandledrejection',(ev)=>{ws.send(JSON.stringify({type:'unhandled-rejection',message:ev.reason?.toString()||'Unknown rejection',priority:'high',timestamp:new Date().toISOString()}));});const obs=new MutationObserver((mutations)=>{mutations.forEach((m)=>{if(m.type==='childList'){m.addedNodes.forEach((n)=>{if(n.nodeType===Node.ELEMENT_NODE){const h=n.querySelectorAll('[data-hydration-error], .hydration-error');if(h.length>0){ws.send(JSON.stringify({type:'hydration-error',message:'DOM에서 Hydration 오류 요소 발견',priority:'high',timestamp:new Date().toISOString()}));}}});}});});obs.observe(document.body,{childList:true,subtree:true,attributes:true});setInterval(()=>{const h=document.querySelectorAll('[data-hydration-error], .hydration-error');if(h.length>0){ws.send(JSON.stringify({type:'hydration-error',message:'주기적 체크에서 Hydration 오류 발견',priority:'high',timestamp:new Date().toISOString()}));}},3000);window.executeFixCommand=function(cmd){console.log('🔧 명령어 실행:',cmd);switch(cmd){case'fix-hydration':console.log('🔄 Hydration 오류 수정: 페이지 새로고침');window.location.reload();break;case'reload':console.log('🔄 페이지 새로고침');window.location.reload();break;case'clear-storage':console.log('🗑️ 로컬 스토리지 클리어');localStorage.clear();sessionStorage.clear();break;default:console.log('❌ 알 수 없는 명령어:',cmd);}};ws.onmessage=(ev)=>{try{const d=JSON.parse(ev.data);if(d.type==='fix-command'&&window.executeFixCommand){window.executeFixCommand(d.command);}}catch(err){console.error('❌ WebSocket 메시지 처리 오류:',err);}};};ws.onclose=()=>{console.log('❌ WebSocket 연결 해제됨');document.body.style.border='3px solid #ef4444';setTimeout(()=>{console.log('🔄 WebSocket 재연결 시도...');location.reload();},3000);};ws.onerror=(err)=>{console.error('❌ WebSocket 오류:',err);document.body.style.border='3px solid #f59e0b';};})();

// 사용법:
// 1. 위 코드를 복사
// 2. http://localhost:3900 페이지에서 F12 누르기
// 3. Console 탭에서 붙여넣기
// 4. Enter 키 누르기
// 5. 페이지가 초록색 테두리로 변하면 성공!
